apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pedidos-express

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - postgres.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml

commonLabels:
  project: pedidos-express
