import type { Product, Order } from './types'

export const mockProducts: Product[] = [
  {
    id: 1,
    name: 'X-Burger Clássico',
    description: 'Hambúrguer artesanal 180g, queijo cheddar, alface, tomate e molho especial',
    price: 28.90,
    category: 'Lanches',
    image_url: '/images/x-burger.jpg',
    available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    name: 'X-Bacon',
    description: 'Hambúrguer 180g, bacon crocante, queijo, cebola caramelizada',
    price: 32.90,
    category: 'Lanches',
    image_url: '/images/x-bacon.jpg',
    available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 3,
    name: 'X-Salada',
    description: 'Hambúrguer 150g, alface, tomate, cebola, picles e maionese',
    price: 24.90,
    category: 'Lanches',
    image_url: '/images/x-salada.jpg',
    available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 4,
    name: 'Hot Dog Tradicional',
    description: 'Salsicha premium, molho, batata palha, milho e ervilha',
    price: 18.90,
    category: 'Lanches',
    image_url: '/images/hotdog.jpg',
    available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 5,
    name: 'Batata Frita Grande',
    description: 'Porção generosa de batatas fritas crocantes',
    price: 19.90,
    category: 'Acompanhamentos',
    image_url: '/images/batata.jpg',
    available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 6,
    name: 'Onion Rings',
    description: 'Anéis de cebola empanados e fritos',
    price: 22.90,
    category: 'Acompanhamentos',
    image_url: '/images/onion-rings.jpg',
    available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 7,
    name: 'Refrigerante Lata',
    description: 'Coca-Cola, Guaraná ou Sprite 350ml',
    price: 6.90,
    category: 'Bebidas',
    image_url: '/images/refrigerante.jpg',
    available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 8,
    name: 'Suco Natural',
    description: 'Laranja, limão ou maracujá 400ml',
    price: 9.90,
    category: 'Bebidas',
    image_url: '/images/suco.jpg',
    available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 9,
    name: 'Milkshake',
    description: 'Chocolate, morango ou baunilha 500ml',
    price: 16.90,
    category: 'Bebidas',
    image_url: '/images/milkshake.jpg',
    available: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 10,
    name: 'Sundae',
    description: 'Sorvete de creme com calda de chocolate ou morango',
    price: 12.90,
    category: 'Sobremesas',
    image_url: '/images/sundae.jpg',
    available: true,
    created_at: new Date().toISOString(),
  },
]

export const mockOrders: Order[] = [
  {
    id: 1,
    customer_name: 'João Silva',
    status: 'preparing',
    total: 61.80,
    notes: 'Sem cebola no hambúrguer',
    created_at: new Date(Date.now() - 15 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 60000).toISOString(),
    items: [
      { id: 1, order_id: 1, product_id: 1, product_name: 'X-Burger Clássico', quantity: 2, unit_price: 28.90, subtotal: 57.80 },
      { id: 2, order_id: 1, product_id: 7, product_name: 'Refrigerante Lata', quantity: 2, unit_price: 6.90, subtotal: 13.80 },
    ],
  },
  {
    id: 2,
    customer_name: 'Maria Santos',
    status: 'pending',
    total: 48.70,
    notes: null,
    created_at: new Date(Date.now() - 5 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 60000).toISOString(),
    items: [
      { id: 3, order_id: 2, product_id: 2, product_name: 'X-Bacon', quantity: 1, unit_price: 32.90, subtotal: 32.90 },
      { id: 4, order_id: 2, product_id: 5, product_name: 'Batata Frita Grande', quantity: 1, unit_price: 19.90, subtotal: 19.90 },
    ],
  },
  {
    id: 3,
    customer_name: 'Pedro Costa',
    status: 'ready',
    total: 35.80,
    notes: 'Capricha no molho!',
    created_at: new Date(Date.now() - 25 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60000).toISOString(),
    items: [
      { id: 5, order_id: 3, product_id: 4, product_name: 'Hot Dog Tradicional', quantity: 1, unit_price: 18.90, subtotal: 18.90 },
      { id: 6, order_id: 3, product_id: 9, product_name: 'Milkshake', quantity: 1, unit_price: 16.90, subtotal: 16.90 },
    ],
  },
]
